version: '3.8'
services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/root/server
    command: npm start
    ports:
      - "4000:4000"
  backend:
    build:
      context: ./backend
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - server