version: '3.8'
services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/server
    command: npm start
    ports:
      - "4000:4000"
  backend:
    build:
      context: ./backend
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./frontend/build:/var/www/html
      - ./deploy/default.conf:/etc/nginx/sites-available/default
    depends_on:
      - server
      - backend