# Generated by Django 3.1.4 on 2021-09-27 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_level', models.IntegerField(choices=[(0, '--Chọn phân cấp đơn vị--'), (1, 'Đơn vị cấp 1'), (2, 'Đơn vị cấp 2'), (3, 'Đơn vị cấp 3')], default=1)),
                ('Sort_id', models.IntegerField(default=0)),
                ('unit_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.unit')),
            ],
            options={
                'verbose_name_plural': 'Đơn vị',
                'unique_together': {('unit_name',)},
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('groups', models.IntegerField(choices=[(0, '--Chọn nhóm quyền--'), (1, 'Quản trị hệ thống'), (2, 'Chủ trì'), (3, 'Thành viên')], default=0)),
                ('city', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='profiles/profile-pic.jpg', null=True, upload_to='media/profiles')),
                ('sort_id', models.IntegerField(default=0)),
                ('is_superuser', models.BooleanField(blank=True, default=False, max_length=30, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, max_length=30, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('unit_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Thông tin tài khoản',
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=1000)),
                ('EventType', models.IntegerField(choices=[(0, 'Ưu tiên cao'), (1, 'Ưu tiên Trung bình'), (2, 'Ưu tiên thấp')], default=2)),
                ('Location', models.CharField(blank=True, max_length=1000, null=True)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('User_control', models.ManyToManyField(related_name='user_control_set', to=settings.AUTH_USER_MODEL)),
                ('User_room', models.ManyToManyField(related_name='user_room_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Phòng họp',
                'unique_together': {('Subject',)},
            },
        ),
    ]
