# Generated by Django 3.1.4 on 2021-09-29 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='User_vip',
            field=models.ManyToManyField(related_name='user_vip_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='media/profiles/logo_qk7.png', null=True, upload_to='media/profiles'),
        ),
    ]
