// frontend/src/components/signup/SignupTypes.js
export const CREATE_USER_SUBMITTED = "CREATE_USER_SUBMITTED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const CREATE_PROFILE_SUBMITTED = "CREATE_PROFILE_SUBMITTED";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_ERROR = "CREATE_PROFILE_ERROR";

export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_REQUEST = "GET_PROFILES_REQUEST";
export const GET_PROFILES_ERROR = "GET_PROFILES_ERROR";
export const UPDATE_PROFILES_SUCCESS = "UPDATE_PROFILES_SUCCESS";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";

export const GET_PROFILE_UNIT_SUCCESS = "GET_PROFILE_UNIT_SUCCESS";
export const GET_PROFILE_UNIT_ERROR = "GET_PROFILE_UNIT_ERROR";


export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_SUBMITTED = "UPDATE_PROFILE_SUBMITTED";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_USER_SUBMITTED = "UPDATE_USER_SUBMITTED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";


export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_REQUEST = "GET_UNITS_REQUEST";
export const GET_UNITS_ERROR = "GET_UNITS_ERROR";

export const CREATE_UNIT_SUBMITTED = "CREATE_UNIT_SUBMITTED";
export const CREATE_UNIT_SUCCESS = "CREATE_UNIT_SUCCESS";
export const CREATE_UNIT_ERROR = "CREATE_UNIT_ERROR";
export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS";

