export const GET_USER_CHAT = "GET_USER_CHAT";
export const GET_ALL_USER_CHAT = "GET_ALL_USER_CHAT";

export const GET_CHAT_GROUPS_ERROR = "GET_CHAT_GROUPS_ERROR";
export const GET_CHAT_GROUP = "GET_CHAT_GROUP";
export const GET_CHAT_GROUPS_SUCCESS = "GET_CHAT_GROUPS_SUCCESS";
export const GET_CHAT_GROUPS_LOAD = "GET_CHAT_GROUPS_LOAD";

export const GET_CHAT_MESSAGES = "GET_CHAT_MESSAGES";
export const POST_CHAT_MESSAGES = "POST_CHAT_MESSAGES";
export const REMOVE_GET_CHAT_MESSAGES = "REMOVE_GET_CHAT_MESSAGES";
