export const GET_CALENDARS = "GET_CALENDARS";
export const ADD_CALENDAR = "ADD_CALENDAR";
export const DELETE_CALENDAR = "DELETE_CALENDAR"; 
export const UPDATE_CALENDAR = "UPDATE_CALENDAR"; 
export const DETAIL_CALENDAR = "DETAIL_CALENDAR"; 
